### PR TITLE
Rewritten to accept name change

### PR DESCRIPTION
**Pull request by istairbn**
After the recent updates broke our fork, I've started again and added our features onto a fresh fork of the existing plugin. 

Main changes:
 - Get CI: Returns XML/JSON of any XLD CI
Use Cases: Copy/Paste identikit CIs, fetch info and scraping 
 - Bulk Undeploy: Pick a folder of applications and an environment. Clears the Environment of any packages found. 
Use Case: Cleaning an Environment of optional applications
 - Add/Remove Member: Update Environments by adding/removing members
Use Case: Adding IIS Databases to environments 
 - Get Application Checklist: Gets the Application checklist (optionally creating release variables) 
Using the Checklist in Gate tasks, informing users of current state - will later create a submit to go with this. 
 - Rename CI: Changes the name of a CI
Use Cases: DR Flip (Prod to DR), naming CI depending on end state after release process
 - Get Environment Delta: Given two environments, outline the differences
Use Cases: Test two Environments are identical, patch list for UAT/Prod differences. 

Also, Get All Versions has the recurse parameter, so it can delve through folders. Set to false by default, but it's very useful.

### CODE REVIEW

**Comment by istairbn** [comment]
Version number upgrade forced me to merge in my newer feature earlier than planned.
Get Environment Hosts:
 - Give it an XL Deploy environment, it returns all the hostnames involved. Can also filter by tag. Useful for many reasons, namely that you can then keep XL Deploy as your golden source for environment set up and poll it for the correct hosts to target at run time. 
Also quite a few codacy whitespace fixes in there.

**Comment by jdewinne** [comment]
Is it possible to split this pull request in separate pull requests? That way we can make a distinction on what should go into the master branch and what not (as I don't think everything should go into the community plugin).

**Comment by istairbn** [comment]
The difficulty mainly lies in the fact that it's been so long since our implementation has been pulled back that I don't have a clean branch with "some" of the features. I could possibly do a fresh pull and add features back in but it'll be a pain. 

What features do you dislike?

**Comment by istairbn** [comment]
Closing - I'll raise smaller ones

**Pull request closed without merging**
