### PR TITLE
Refactor task definitions

### PR DESCRIPTION
**Pull request by demobox**
Pulling `xldeployServer`, `username` and `password` into a base virtual task.

**Note:** Should not be merged before #4, as this duplicates the changes in https://github.com/demobox/xlr-xldeploy-plugin/commit/4c5fbb08ab88865beacf6d8bad4007c4d6e77c1c.

### CODE REVIEW

**Comment by demobox** [comment]
@bmoussaud @jdewinne Ping ;-)

**Comment by demobox** [comment]
@bmoussaud @jdewinne @mpvvliet Quick ping?

**Comment by demobox** [comment]
@jdewinne: Thanks! Now #4 is broken, though :-(

**Comment by jdewinne** [comment]
Oh, damn, now I see you asked for this, to merge #4 first :-(
Suggestions on how to fix?

**Pull request merged**
