### PR TITLE
Updating labels and formatting in task definitions

### PR DESCRIPTION
**Pull request by demobox**
@jdewinne Ping?

### CODE REVIEW

**Comment by demobox** [comment]
@jdewinne @mpvvliet Quick ping?

**Comment by demobox** [comment]
@jdewinne Quick ping..?

**Comment by jdewinne** [comment]
Sorry for the delay, I thought this was conflicting for some reason.

**Comment by demobox** [comment]
> Sorry for the delay, I thought this was conflicting for some reason.

It was ;-) I rebased it yesterday and resolved the conflicts...

**Pull request merged**
